### PR TITLE
added an "Asm" language to allow customizing build flags for asm sources

### PR DESCRIPTION
**Pull request by mokus0**
As mentioned in my other PR, I'm building a bare-metal project using shake-language-c, and I found it useful to add an Asm language, so I can configure different build flags for asm files.

### CODE REVIEW

**Comment by kaoskorobase** [comment]
Thanks and sorry for the delay!

**Comment by mokus0** [comment]
Any idea when you might have a chance to make a Hackage release with this?

Thanks!

**Comment by mokus0** [comment]
ping?

**Comment by kaoskorobase** [comment]
Hey sorry for being so slow, I'll push a new release ASAP.

**Pull request merged**
